### PR TITLE
chore: license.txt位置可配置以解决子项目下构建失败问题

### PR DESCRIPTION
**Pull request by qxo**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style
- [ ] Refactor
- [ ] Doc
- [X] Other, please describe:

**The description of the PR:**

 license.txt位置可配置以解决子项目下构建失败问题
```
[ERROR] Failed to execute goal com.mycila:license-maven-plugin:4.3:check (default) on project dynamic-datasource-spring-boot-starter: Execution default of goal com.mycila:license-maven-plugin:4.3:check failed: Cannot read header document license.txt. Cause: Resource license.txt not found in file system, classpath or URL: no protocol: license.txt -> [Help 1]
```

**Other information:**

### CODE REVIEW

**Review by linghengqian — COMMENTED** [review]
- Why build subprojects independently? This often breaks the local dependency chain. 

- We already have https://github.com/baomidou/dynamic-datasource/blob/master/CONTRIBUTING.md .

**Comment by qxo** [comment]
ok




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rossen ***@***.***&gt;; 
发送时间: 2023年12月25日(星期一) 下午3:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [baomidou/dynamic-datasource] chore: license.txt位置可配置以解决子项目下构建失败问题 (PR #610)





 
@linghengqian commented on this pull request.
  
 
Why build subprojects independently? This often breaks the local dependency chain.
 
 
 
We already have https://github.com/baomidou/dynamic-datasource/blob/master/CONTRIBUTING.md .

**Comment by huayanYu** [comment]
没看懂, 我现在构建似乎也没问题啊

**Comment by qxo** [comment]
> 没看懂, 我现在构建似乎也没问题啊

在子项目直接命令行构建会失败

**Comment by linghengqian** [comment]
> > 没看懂, 我现在构建似乎也没问题啊
> 
> 在子项目直接命令行构建会失败

- I would not approve of merging this PR if it was for such a purpose. This goes against the design of multi-module Maven projects.

**Comment by qxo** [comment]
> > > 没看懂, 我现在构建似乎也没问题啊
> > 
> > 
> > 在子项目直接命令行构建会失败
> 
> * I would not approve of merging this PR if it was for such a purpose. This goes against the design of multi-module Maven projects.

在子项目目录下命令行

dynamic-datasource-creator>mvn install -Dmaven.test.skip

===>
```
[ERROR] Failed to execute goal com.mycila:license-maven-plugin:4.3:check (default) on project dynamic-datasource-creator: Execution default of goal com.mycila:license-maven-plugin:4.3:check failed: Cannot read header document license.txt. Cause: Resource license.txt not found in file system, classpath or URL: no protocol: license.txt ->
```

**Comment by linghengqian** [comment]
> > > > 没看懂, 我现在构建似乎也没问题啊
> > > 
> > > 
> > > 在子项目直接命令行构建会失败
> > 
> > * I would not approve of merging this PR if it was for such a purpose. This goes against the design of multi-module Maven projects.
> 
> 在子项目目录下命令行
> 
> dynamic-datasource-creator>mvn install -Dmaven.test.skip
> 
> ===>
> ```
> [ERROR] Failed to execute goal com.mycila:license-maven-plugin:4.3:check (default) on project dynamic-datasource-creator: Execution default of goal com.mycila:license-maven-plugin:4.3:check failed: Cannot read header document license.txt. Cause: Resource license.txt not found in file system, classpath or URL: no protocol: license.txt ->
> ```

- I believe this is expected behavior - for multi-module Maven projects, configuration constraints on plugins are all located in the top-level POM. Subprojects themselves should not know about these configurations unless they are explicitly inherited.

**Pull request closed without merging**
